In [11]:
import numpy as np

In [12]:
# python list
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy Array
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [13]:
%%time
# python
result = 0
for x, w in zip(arr1, arr2):
    result += x*w
print(result)

833332333333500000
CPU times: user 174 ms, sys: 4.96 ms, total: 179 ms
Wall time: 177 ms


In [14]:
%%time
# numpy
np.dot(arr1_np, arr2_np)

CPU times: user 2.78 ms, sys: 521 µs, total: 3.3 ms
Wall time: 1.8 ms


833332333333500000

In [15]:
%%time
# numpy
(arr1_np*arr2_np).sum()

CPU times: user 0 ns, sys: 19.2 ms, total: 19.2 ms
Wall time: 14.9 ms


833332333333500000

In [16]:
# show datatype
weights.dtype

NameError: name 'weights' is not defined

In [17]:
# 1D array
weights = np.array([0.3, 0.2, 0.5])

# 2D array
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

climate_data.shape
# 3D array 
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

arr3.shape

(2, 2, 3)

In [18]:
# We can use the np.matmul function or the @ operator to perform matrix multiplication.

np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [19]:
# also 

climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [20]:
# Working with CSV data files


# read txt file
climate_txt = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)
climate_txt

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [21]:
climate_txt.shape

(10000, 3)

In [22]:
weight = np.array([0.3, 0.2, 0.5])

In [23]:
# matrix multiplication

yeild = climate_txt @ weight
yeild

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [24]:
yeild.shape

(10000,)

In [27]:
# re shape
yeild_shape_change = yeild.reshape(10000,1)
yeild_shape_change

array([[72.2],
       [59.7],
       [65.2],
       ...,
       [71.1],
       [80.7],
       [73.4]])

In [37]:
# add column

climate_with_yeild = np.concatenate((climate_txt, yeild_shape_change),axis=1)
climate_with_yeild

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [38]:
# save txt

save_climate = np.savetxt('climate_result.txt', 
                          climate_with_yeild, 
                          fmt='%.2f', 
                          header='temperature,rainfall,humidity,yeilds',
                          comments=''
                         )
save_climate

In [39]:
# Arithmetic operations and comparison
arr1=np.array([[1,2,3],
              [4,5,6]])
arr2=np.array([[7,8,9],
              [4,5,6]])

In [41]:
# Adding scaler
arr1+3

array([[4, 5, 6],
       [7, 8, 9]])

In [42]:
arr1+arr2

array([[ 8, 10, 12],
       [ 8, 10, 12]])

In [43]:
# Array comparison
arr1==arr2

array([[False, False, False],
       [ True,  True,  True]])

In [47]:
(arr1==arr2).sum()

3

In [48]:
# Array indexing and slicing
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [49]:
# Single element
arr3[1,1,2]

36.0

In [51]:
# Subarray using ranges
arr3[1:,0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

In [52]:
# Mixing indices and ranges
arr3[1:, 1, :3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [ ]:
# Other ways of creating Numpy arrays

In [53]:
# All zeros
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [54]:
# All ones
np.ones([2, 2, 3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [55]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
# Random vector
np.random.rand(5)

array([0.34217778, 0.27701296, 0.26823672, 0.09442155, 0.46437217])

In [57]:
# Random matrix
np.random.randn(2, 3) # rand vs. randn - what's the difference?

array([[ 0.94511041,  0.26904125,  1.4022246 ],
       [-0.34451128,  0.41919957, -0.08924299]])

In [58]:
# Fixed value
np.full([2, 3], 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [59]:
# Range with start, end and step
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [60]:
# Equally spaced numbers in a range
np.linspace(3, 27, 9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])