In [1]:
import numpy as np

In [2]:
# python list
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy Array
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [3]:
%%time
# python
result = 0
for x, w in zip(arr1, arr2):
    result += x*w
print(result)

833332333333500000
CPU times: user 217 ms, sys: 4.32 ms, total: 221 ms
Wall time: 220 ms


In [4]:
%%time
# numpy
np.dot(arr1_np, arr2_np)

CPU times: user 8.34 ms, sys: 61 µs, total: 8.4 ms
Wall time: 6.11 ms


833332333333500000

In [5]:
%%time
# numpy
(arr1_np*arr2_np).sum()

CPU times: user 10 ms, sys: 6.47 ms, total: 16.5 ms
Wall time: 34.9 ms


833332333333500000

In [7]:
# show datatype
weights.dtype

dtype('float64')

In [6]:
# 1D array
weights = np.array([0.3, 0.2, 0.5])

# 2D array
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

climate_data.shape
# 3D array 
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

arr3.shape

(2, 2, 3)

In [8]:
# We can use the np.matmul function or the @ operator to perform matrix multiplication.

np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [19]:
# also 

climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [31]:
# Working with CSV data files


# read txt file
climate_txt = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)
climate_txt

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [13]:
climate_txt.shape

(10000, 3)

In [19]:
weight = np.array([0.3, 0.2, 0.5])

In [24]:
# matrix multiplication

yeild = climate_txt @ weight
yeild

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [25]:
yeild.shape

(10000,)

In [26]:
# re shape
yeild_shape_change = yelds.reshape(10000,1)
yeild_shape_change

array([[72.2],
       [59.7],
       [65.2],
       ...,
       [71.1],
       [80.7],
       [73.4]])

In [29]:
# add column

climate_with_yeild = np.concatenate((climate_txt, yelds_shape_change),axis=1)
climate_with_yeild

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [34]:
# save txt

save_climate = np.savetxt('climate_result.txt', 
                          climate_with_yeild, 
                          fmt='%.2f', 
                          header='temperature,rainfall,humidity,yeilds',
                          comments=''
                         )
save_climate